### ISSUE TITLE
Illegal instruction (core dumped) when using 'alive6 eth0' command on Host A, B and C

### ISSUE THREAD

**Issue by Abhayanath** [RIPE-NCC/ipv6-security-lab#18]
I am unable to execute the following commands. I get the illegal instruction error

root@hostA:~# alive6 eth0
Illegal instruction (core dumped)
root@hostA:~# alive6 -h
Illegal instruction (core dumped)
root@hostA:~# alive6 eth0 -vv
Illegal instruction (core dumped)

![alive6_error1](https://github.com/user-attachments/assets/6d5a345e-6a65-4ff7-affa-8ad38b499371)

**Comment by oskar456** [comment]
Thanks for the report. This might be fixed in the newest version of THC-IPv6:
https://github.com/vanhauser-thc/thc-ipv6/commit/413c55e667faa368934708aa9acf886e6732e32b

Can you try [running the development version](https://github.com/RIPE-NCC/ipv6-security-lab?tab=readme-ov-file#running-the-development-version) by downloading the repository and running `vagrant up` there? It should rebuild everything on your computer.

**Comment by Abhayanath** [comment]
Hello Ondrej,

Thank you for the response. I will go through the install instructions and
will try with the newest version and will let you know.

Best Regards,
Abhay.

**Comment by Abhayanath** [comment]
Thank you Ondrej. I didn't get the time to install the development version.
I will continue the training and will wait for your update when it's fixed.

Best Regards,

Abhay

**Comment by oskar456** [comment]
Hello again,

I have published the new version. So it should be enough to upgrade to the new version by running:
```
vagrant destroy
vagrant box update
vagrant up
```

I am closing this now. If you encounter the issue again, please reopen it.
